//Randcase example
module r_case;
  initial begin
    $display("Random data will be generated by simulator");
    $display("data from 0 to 3 then it will display randcase output");

    for (int i = 0; i < 6; i++) begin
      randcase
      0: $display("Output of randcase 0"); // Case 0 with weight 0 // Probability is 0
      1: $display("Output of randcase 1"); // Case 1 with weight 1 // Probability is 1/6
      2: $display("Output of randcase 2"); // Case 2 with weight 2 // Probability is 2/6
      3: $display("Output of randcase 3"); // Case 3 with weight 3 // Probability is 3/6
      endcase
    end
  end

endmodule
